### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by MarcinKosinski** [williamxie11/glassdoor-interview-scraper#1]
Hi,

Have you seen such an issue with your script?

````{}
 python scraper_v1.2.py 
Traceback (most recent call last):
  File "scraper_v1.2.py", line 140, in <module>
    driver = init_driver()
  File "scraper_v1.2.py", line 31, in init_driver
    driver = webdriver.Chrome(executable_path = "./chromedriver")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

````

**Comment by williamxie11** [comment]
Looks like an issue with the chromedriver. What OS are you trying to run this on?
You might want to download a different chromedriver based on where you are running this from (the one in the repo ran on Mac).

https://chromedriver.storage.googleapis.com/index.html?path=2.26/

**Comment by MarcinKosinski** [comment]
Yes u didn't had `import os`. I have also found more issues with this code to work withthe current version of glassdoor

**Comment by MarcinKosinski** [comment]
https://github.com/williamxie11/glassdoor-interview-scraper/blob/master/scraper_v1.2.py#L112
there is `_P` now instead of `_IP`
